/**
 * Short definitions shown when hovering, focusing or tapping a dotted term. When `anchor` is set, the term
 * links to that entry of a single reference: the Google Machine Learning Glossary (anchors checked against
 * the live page). Business terms without an entry there have no anchor.
 */
export const GLOSSARY = {
  url: "https://developers.google.com/machine-learning/glossary",
  source: "Google Machine Learning Glossary",
  terms: {
    churn: {
      title: "Churn",
      text: "A client leaving the bank (closing accounts or moving assets away).",
    },
    synthetic: {
      title: "Synthetic data",
      text: "Fictitious clients generated by this page: realistic patterns, no real bank, client or person.",
    },
    split: {
      title: "Learn / test split",
      text: "Part of the clients is used to learn; the rest is kept aside to check the model on clients it has never seen.",
      anchor: "test-set",
    },
    tree: {
      title: "Decision tree",
      text: "A model that asks a series of yes/no questions about a client (e.g. “complaint?”) and ends in a group with a known share of leavers.",
      anchor: "decision-tree",
    },
    depth: {
      title: "Depth",
      text: "How many questions the tree may ask in a row. More depth gives more detailed groups, and more risk of overfitting.",
      anchor: "decision-tree",
    },
    mingroup: {
      title: "Minimum group size",
      text: "The smallest share of clients a rule may describe. A rule covering 2 clients is an anecdote, not a pattern.",
      anchor: "leaf",
    },
    anomaly: {
      title: "Anomaly detection",
      text: "Models that look for unusual cases (e.g. possible fraud) rather than predicting a known outcome.",
      anchor: "anomaly-detection",
    },
    iforest: {
      title: "Isolation Forest",
      text: "An anomaly-detection model: it isolates clients with random splits; the fewer splits needed, the more unusual the client.",
      anchor: "anomaly-detection",
    },
    auc: {
      title: "Ranking score (AUC)",
      text: "Area Under the ROC Curve: the chance that the model ranks a random leaver above a random loyal client. 50% = coin flip, 100% = perfect.",
      anchor: "auc-area-under-the-roc-curve",
    },
    cv: {
      title: "Cross-validation",
      text: "Hide part of the learning data, learn on the rest, score on the hidden part; repeat and average. It measures quality without touching the final test set.",
      anchor: "k-fold-cross-validation",
    },
    overfitting: {
      title: "Overfitting",
      text: "The model learns the noise of past data by heart: excellent on the past, worse on new clients.",
      anchor: "overfitting",
    },
    certainty: {
      title: "False certainty",
      text: "An overfitted model gives extreme 0% or 100% risks that new data does not support.",
      anchor: "overfitting",
    },
    sensitivity: {
      title: "Sensitivity",
      text: "Share of real leavers the model flags. Also called recall or true positive rate.",
      anchor: "recall",
    },
    specificity: {
      title: "Specificity",
      text: "Share of loyal clients the model leaves alone. 1 − specificity is the false-alarm rate.",
      anchor: "false-positive-rate-fpr",
    },
    confusion: {
      title: "Confusion matrix",
      text: "A table crossing what the model said with what really happened: caught, false alarms, missed, left alone.",
      anchor: "confusion-matrix",
    },
    falsealarm: {
      title: "False alarm",
      text: "A loyal client flagged as leaving (a false positive): one call for nothing.",
      anchor: "false-positive-fp",
    },
    missed: {
      title: "Missed leaver",
      text: "A client who left but was not flagged (a false negative): the costly error.",
      anchor: "false-negative-fn",
    },
    roc: {
      title: "ROC curve",
      text: "Receiver Operating Characteristic: leavers caught against false alarms, for every possible threshold.",
      anchor: "roc-receiver-operating-characteristic-curve",
    },
    threshold: {
      title: "Threshold",
      text: "The risk level above which we act (call the client). Lower = more calls, more leavers caught, more false alarms.",
      anchor: "classification-threshold",
    },
    elbow: {
      title: "Elbow",
      text: "The point of the ROC curve furthest above the coin-flip diagonal: the best statistical balance between catching leavers and false alarms (Youden's J).",
      anchor: "roc-receiver-operating-characteristic-curve",
    },
    accuracy: {
      title: "Accuracy",
      text: "Share of all predictions that are right. Misleading when leavers are rare: saying “nobody leaves” is already 90% accurate.",
      anchor: "accuracy",
    },
    netvalue: {
      title: "Net value",
      text: "Revenue kept thanks to the calls, minus the cost of the calls, using the business assumptions below.",
    },
    drift: {
      title: "Data drift",
      text: "When the data arriving in production no longer looks like the data the model learned from.",
      anchor: "training-serving-skew",
    },
    psi: {
      title: "Population Stability Index (PSI)",
      text: "How much a signal's distribution moved since the model was trained. Below 0.10 stable, 0.10–0.25 watch, above 0.25 alert.",
      anchor: "training-serving-skew",
    },
    inference: {
      title: "Inference",
      text: "Using a trained model to score new clients. The model no longer learns; it only applies what it learned.",
      anchor: "inference",
    },
  },
};
